-- =============================================================
-- Migration : Tables inscriptions_auto + inscriptions_auto_pays
-- =============================================================
-- Paramétrage annuel des pré-inscriptions automatiques :
--   - inscriptions_auto : 1 ligne par (membre_email, annee)
--     → champs globaux : france, étranger, quantités, mode paiement/envoi
--   - inscriptions_auto_pays : 1 ligne par (membre_email, annee, pays_nom)
--     → sélection fine par pays étranger avec quantités spécifiques
-- =============================================================

-- 1. Table inscriptions_auto
CREATE TABLE inscriptions_auto (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    membre_email            TEXT NOT NULL,
    annee                   INTEGER NOT NULL,
    france                  BOOLEAN NOT NULL DEFAULT FALSE,
    nb_normaux_fr           INTEGER NOT NULL DEFAULT 1,
    nb_variantes_fr         INTEGER NOT NULL DEFAULT 0,
    etranger                BOOLEAN NOT NULL DEFAULT FALSE,
    nb_normaux_etr_defaut   INTEGER NOT NULL DEFAULT 1,
    nb_variantes_etr_defaut INTEGER NOT NULL DEFAULT 0,
    mode_paiement           TEXT NOT NULL DEFAULT 'PayPal' CHECK (mode_paiement IN ('PayPal', 'Chèque')),
    mode_envoi              TEXT NOT NULL DEFAULT 'Normal' CHECK (mode_envoi IN ('Normal', 'Suivi', 'R1', 'R2', 'R3')),
    UNIQUE(membre_email, annee)
);

-- 2. Table inscriptions_auto_pays
CREATE TABLE inscriptions_auto_pays (
    id               INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    membre_email     TEXT NOT NULL,
    annee            INTEGER NOT NULL,
    pays_nom         TEXT NOT NULL,
    nb_normaux       INTEGER NOT NULL DEFAULT 1,
    nb_variantes     INTEGER NOT NULL DEFAULT 0,
    UNIQUE(membre_email, annee, pays_nom)
);

-- 3. Index
CREATE INDEX inscriptions_auto_annee_idx ON inscriptions_auto (annee);
CREATE INDEX inscriptions_auto_pays_annee_idx ON inscriptions_auto_pays (annee);

-- 4. RLS — inscriptions_auto
ALTER TABLE inscriptions_auto ENABLE ROW LEVEL SECURITY;

CREATE POLICY inscriptions_auto_select ON inscriptions_auto
    FOR SELECT
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email')
    );

CREATE POLICY inscriptions_auto_admin_insert ON inscriptions_auto
    FOR INSERT
    WITH CHECK (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

CREATE POLICY inscriptions_auto_admin_update ON inscriptions_auto
    FOR UPDATE
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    )
    WITH CHECK (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

CREATE POLICY inscriptions_auto_admin_delete ON inscriptions_auto
    FOR DELETE
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

-- 5. RLS — inscriptions_auto_pays
ALTER TABLE inscriptions_auto_pays ENABLE ROW LEVEL SECURITY;

CREATE POLICY inscriptions_auto_pays_select ON inscriptions_auto_pays
    FOR SELECT
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email')
    );

CREATE POLICY inscriptions_auto_pays_admin_insert ON inscriptions_auto_pays
    FOR INSERT
    WITH CHECK (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

CREATE POLICY inscriptions_auto_pays_admin_update ON inscriptions_auto_pays
    FOR UPDATE
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    )
    WITH CHECK (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

CREATE POLICY inscriptions_auto_pays_admin_delete ON inscriptions_auto_pays
    FOR DELETE
    USING (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );

-- 6. Policy manquante sur table inscriptions existante (prérequis)
CREATE POLICY inscriptions_insert_admin ON inscriptions
    FOR INSERT
    WITH CHECK (
        EXISTS (SELECT 1 FROM membres WHERE email = auth.jwt() ->> 'email' AND role = 'admin')
    );
